; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./app
data_dir = data

[env]
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder, send_on_enter
upload_protocol = esptool
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	olikraus/U8g2@^2.36.5
	https://github.com/dplasa/FTPClientServer.git
	https://github.com/jahrulnr/esp32-notification.git
	https://github.com/jahrulnr/esp32-microphone.git
	https://github.com/jahrulnr/esp32-picoTTS.git
	https://github.com/jahrulnr/esp32-speaker.git
	bblanchon/ArduinoJson@^7.0.3
build_unflags =
	-Werror=all
	-fno-exceptions
build_flags =
	-DCORE_DEBUG_LEVEL=3
	-DLOG_LOCAL_LEVEL=5 ; ESP_LOG*
	-DCONFIG_ASYNC_TCP_PRIORITY=6
	-DCONFIG_ASYNC_TCP_STACK_SIZE=5128
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DDEFAULT_MAX_WS_CLIENTS=2
	-DWS_MAX_QUEUED_MESSAGES=32
	-DCONFIG_ARDUINO_ISR_IRAM=0
	-DCONFIG_SPIRAM_USE_MALLOC=1
	-DCONFIG_ESP32S3_DATA_CACHE_64KB=1
	-DCONFIG_ESP32S3_DATA_CACHE_LINE_64B=1
	-DCONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=1
	-DCONFIG_SR_VADN_VADNET1_MEDIUM=1
	-DCONFIG_SR_NSN_NSNET2=1
	-DARDUINO_PARTITION_esp_sr_16
	-DCONFIG_FLASH_COCO_DETECT_YOLO11N_320_S8_V3
	-DCONFIG_COCO_DETECT_MODEL_IN_FLASH_PARTITION
	-DCONFIG_PEDESTRIAN_DETECT_MODEL_IN_FLASH_PARTITION
	-DCONFIG_APP_BUILD_TYPE_RAM=1
	-DCONFIG_NEWLIB_NANO_FORMAT=1
	-DCONFIG_ESP_SYSTEM_PANIC_PRINT_HALT=1
	-DCONFIG_ESP_DEBUG_STUBS_ENABLE=
	-DESP_NN
	-Wno-maybe-uninitialized
	-Wno-missing-field-initializers
	-Wno-error=sign-compare
	-Wno-error=double-promotion
	-Wno-type-limits
	; -mfix-esp32-psram-cache-issue
	; -mfix-esp32-psram-cache-strategy=memw
	-std=gnu++17
	-fexceptions

extra_scripts =
	tools/partition_manager.py
platform_packages =
	tool-esp32partitiontool@https://github.com/serifpersia/esp32partitiontool/releases/download/v1.4.5/esp32partitiontool-platformio.zip
	platformio/tool-mklittlefs@^1.203.210628

[env:esp32s3dev]
platform = https://github.com/pioarduino/platform-espressif32/archive/refs/tags/55.03.32.tar.gz
board = esp32s3-n16r8
board_build.partitions = custom.csv
build_flags =
	${env.build_flags}