#include "Mochi.h"

namespace Mochi {
	int frame = 0;

	void sendBuffer(U8G2_SSD1306_128X64_NONAME_F_HW_I2C* display){
		display->clearBuffer();					// clear the internal memory
		display->drawXBMP(0, 0, 128, 64, epd_bitmap_allArray[frame]); // draw fullscreen image generated by image2cpp website
		display->sendBuffer();					// transfer internal memory to the display
	}

	void drawFrame(U8G2_SSD1306_128X64_NONAME_F_HW_I2C* display) { // main loop
		frame = 0;

		do{
			sendBuffer(display);
			taskYIELD();
		}
		
		while(90 > ++frame); // increase the frame number
	}
}