#pragma once

#ifdef ESP32S3_DEVKITC1_N16R8
// #define MIC_TYPE MIC_TYPE_ANALOG
#define MIC_TYPE MIC_I2S

#define SCL_PIN 3
#define SDA_PIN 46
// #define BUTTON_PIN 0
#define BUTTON_PIN 20

#define MIC_SCK GPIO_NUM_1
#define MIC_WS  GPIO_NUM_0
#define MIC_DIN GPIO_NUM_45

#define I2S_SPEAKER_DOUT_PIN GPIO_NUM_14
#define I2S_SPEAKER_BCLK_PIN GPIO_NUM_47
#define I2S_SPEAKER_LRC_PIN GPIO_NUM_21
#define I2S_SPEAKER_PORT I2S_NUM_1

#elif SEED_XIAO_ESP32S3
#define SCL_PIN 5
#define SDA_PIN 6
// #define BUTTON_PIN 0
#define BUTTON_PIN 1

#define MIC_TYPE MIC_PDM
#define MIC_SCK GPIO_NUM_42
#define MIC_WS  GPIO_NUM_NC
#define MIC_DIN GPIO_NUM_41

#define I2S_SPEAKER_DOUT_PIN GPIO_NUM_2
#define I2S_SPEAKER_BCLK_PIN GPIO_NUM_3
#define I2S_SPEAKER_LRC_PIN GPIO_NUM_4
#define I2S_SPEAKER_PORT I2S_NUM_1
#endif